/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 265d8cb69d105d6f2e5f7a391a3dd9d1)
interface __BaseEnv_Env {
	PROJECT_ASSETS: R2Bucket;
	SHARED_ASSETS: R2Bucket;
	CLIENT_ID: "60987";
	FRONTEND_URL: "https://cascade.sheepex.net";
	OSU_REDIRECT_URI: "https://mania-editor.noahcraft01.workers.dev/auth/osu/callback";
	SUPABASE_URL: "https://splqsxhwdusjeqthinxz.supabase.co";
	SUPABASE_STORAGE_FALLBACK: "true";
	SUPABASE_STORAGE_ALLOWANCE_BYTES: "1073741824";
	R2_STORAGE_ALLOWANCE_BYTES: "10737418240";
	MAX_ASSET_BYTES: "62914560";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLIENT_ID" | "FRONTEND_URL" | "OSU_REDIRECT_URI" | "SUPABASE_URL" | "SUPABASE_STORAGE_FALLBACK" | "SUPABASE_STORAGE_ALLOWANCE_BYTES" | "R2_STORAGE_ALLOWANCE_BYTES" | "MAX_ASSET_BYTES">> {}
}
